# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(b'contract', b'umowa'), (b'job', b'zlecenie')], default=b'contract', max_length=20)),
                ('date_from', models.DateField(blank=True, default=b'2017-11-30', null=True)),
                ('data_to', models.DateField(blank=True, default=b'2017-11-30', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent_payment', models.CharField(max_length=5)),
                ('hours', models.CharField(max_length=4)),
                ('charge', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('decision', models.ManyToManyField(to='care_point.Decision')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Point_of_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sname', models.CharField(max_length=30)),
                ('pesel', models.CharField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[(b'contract', b'umowa'), (b'job', b'zlecenie')], default=b'contract', max_length=15)),
                ('date_from', models.DateField(blank=True, default=b'2017-11-30', null=True)),
                ('data_to', models.DateField(blank=True, default=b'2017-11-30', null=True)),
                ('working_hours', models.FloatField()),
                ('hours_from', models.TimeField()),
                ('hours_to', models.TimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='point_of_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='decision',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Contract'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='point_of_care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_point.Point_of_care'),
        ),
        migrations.AddField(
            model_name='activity',
            name='decision',
            field=models.ManyToManyField(to='care_point.Decision'),
        ),
    ]
