# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0002_auto_20171130_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='data_to',
            new_name='date_to',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='caregiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksheet',
            name='ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='care_point.Ward'),
            preserve_default=False,
        ),
    ]
