# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0003_auto_20171130_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='procent_payment',
            new_name='percent_payment',
        ),
        migrations.AlterField(
            model_name='activity',
            name='decision',
            field=models.ManyToManyField(blank=True, null=True, to='care_point.Decision'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='decision',
            field=models.ManyToManyField(blank=True, null=True, to='care_point.Decision'),
        ),
    ]
