# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0005_auto_20171201_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Caregiver'),
        ),
    ]
