# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0007_auto_20171203_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='data_to',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='date_to',
            field=models.DateField(blank=True, default=b'2017-12-04', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default=b'2017-12-04', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default=b'2017-12-04', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date_from',
            field=models.DateField(blank=True, default=b'2017-12-04', null=True),
        ),
    ]
