# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0010_auto_20171204_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
