# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0011_auto_20171204_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='hours_from',
            field=models.TimeField(default=b'20:00'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hours_to',
            field=models.TimeField(default=b'20:00'),
        ),
    ]
