# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0012_auto_20171204_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hours_from',
            field=models.TimeField(default=b'8:00'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hours_to',
            field=models.TimeField(default=b'10:00'),
        ),
    ]
