# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0014_auto_20171204_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='care_point.Decision'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_from',
            field=models.DateField(blank=True, default=b'2017-12-05', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_to',
            field=models.DateField(blank=True, default=b'2017-12-05', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date_from',
            field=models.DateField(blank=True, default=b'2017-12-05', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='date_to',
            field=models.DateField(blank=True, default=b'2017-12-05', null=True),
        ),
    ]
