# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0016_auto_20171212_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='hours_from',
            new_name='hour_from',
        ),
        migrations.RenameField(
            model_name='worksheet',
            old_name='hours_to',
            new_name='hour_to',
        ),
    ]
