# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0017_auto_20171212_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='hour_from',
            field=models.DateField(blank=True, default=b'2017-12-12', null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hour_to',
            field=models.DateField(blank=True, default=b'2017-12-12', null=True),
        ),
    ]
