# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_point', '0018_auto_20171212_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='hour_from',
            field=models.TimeField(default=b'8:00'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='hour_to',
            field=models.TimeField(default=b'10:00'),
        ),
    ]
